#!/usr/bin/env php
<?php

require_once 'Summarizer.php';

if (empty($repositories = Summarizer::findRepositories())) {
	throw new RuntimeException('Folder `repositories` does not contain any GIT repository.');
}

$calendar = Summarizer::prepareCalendar(Summarizer::exportContributionsDates($repositories));

ob_start();
include 'template.php';
file_put_contents('outputs/output.html', ob_get_clean());